#Bibliotecas

In [218]:
import pandas as pd
import requests

#📌 Extracción

In [219]:
url = "https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json"

response = requests.get(url)
data = response.json()

df = pd.DataFrame(data)
df.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [220]:
df.dtypes

customerID    object
Churn         object
customer      object
phone         object
internet      object
account       object
dtype: object

In [221]:
df.iloc[0]

customerID                                           0002-ORFBO
Churn                                                        No
customer      {'gender': 'Female', 'SeniorCitizen': 0, 'Part...
phone            {'PhoneService': 'Yes', 'MultipleLines': 'No'}
internet      {'InternetService': 'DSL', 'OnlineSecurity': '...
account       {'Contract': 'One year', 'PaperlessBilling': '...
Name: 0, dtype: object

In [222]:
df = pd.json_normalize(data)
df.head()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

#🔧 Transformación

 #### ✅ Explorar las columnas del dataset y verificar sus tipos de datos.

In [223]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [224]:
df.dtypes

customerID                    object
Churn                         object
customer.gender               object
customer.SeniorCitizen         int64
customer.Partner              object
customer.Dependents           object
customer.tenure                int64
phone.PhoneService            object
phone.MultipleLines           object
internet.InternetService      object
internet.OnlineSecurity       object
internet.OnlineBackup         object
internet.DeviceProtection     object
internet.TechSupport          object
internet.StreamingTV          object
internet.StreamingMovies      object
account.Contract              object
account.PaperlessBilling      object
account.PaymentMethod         object
account.Charges.Monthly      float64
account.Charges.Total         object
dtype: object

In [225]:
df.columns

Index(['customerID', 'Churn', 'customer.gender', 'customer.SeniorCitizen',
       'customer.Partner', 'customer.Dependents', 'customer.tenure',
       'phone.PhoneService', 'phone.MultipleLines', 'internet.InternetService',
       'internet.OnlineSecurity', 'internet.OnlineBackup',
       'internet.DeviceProtection', 'internet.TechSupport',
       'internet.StreamingTV', 'internet.StreamingMovies', 'account.Contract',
       'account.PaperlessBilling', 'account.PaymentMethod',
       'account.Charges.Monthly', 'account.Charges.Total'],
      dtype='object')

In [226]:
df.shape

(7267, 21)

#### ✅ Consultar el diccionario para comprender mejor el significado de las variables.

#### Diccionario de datos

- `customerID`: número de identificación único de cada cliente
- `Churn`: si el cliente dejó o no la empresa
- `gender`: género (masculino y femenino)
- `SeniorCitizen`: información sobre si un cliente tiene o no una edad igual o mayor a 65 años
- `Partner`: si el cliente tiene o no una pareja
- `Dependents`: si el cliente tiene o no dependientes
- `tenure`: meses de contrato del cliente
- `PhoneService`: suscripción al servicio telefónico
- `MultipleLines`: suscripción a más de una línea telefónica
- `InternetService`: suscripción a un proveedor de internet
- `OnlineSecurity`: suscripción adicional de seguridad en línea
- `OnlineBackup`: suscripción adicional de respaldo en línea
- `DeviceProtection`: suscripción adicional de protección del dispositivo
- `TechSupport`: suscripción adicional de soporte técnico, menor tiempo de espera
- `StreamingTV`: suscripción de televisión por cable
- `StreamingMovies`: suscripción de streaming de películas
- `Contract`: tipo de contrato
- `PaperlessBilling`: si el cliente prefiere recibir la factura en línea
- `PaymentMethod`: forma de pago
- `Charges.Monthly`: total de todos los servicios del cliente por mes
- `Charges.Total`: total gastado por el cliente

#### ✅ Identificar las columnas más relevantes para el análisis de evasión.

In [227]:
customer_cols = [c for c in df.columns if c.startswith("customer.")]
phone_cols    = [c for c in df.columns if c.startswith("phone.")]
internet_cols = [c for c in df.columns if c.startswith("internet.")]
account_cols  = [c for c in df.columns if c.startswith("account.")]

print("Target:", "Churn")
print("ID:", "customerID")

print("\nCustomer (demografía/tenure):", customer_cols)
print("\nPhone (telefonía):", phone_cols)
print("\nInternet (servicios internet):", internet_cols)
print("\nAccount (contrato/pago/cargos):", account_cols)

Target: Churn
ID: customerID

Customer (demografía/tenure): ['customer.gender', 'customer.SeniorCitizen', 'customer.Partner', 'customer.Dependents', 'customer.tenure']

Phone (telefonía): ['phone.PhoneService', 'phone.MultipleLines']

Internet (servicios internet): ['internet.InternetService', 'internet.OnlineSecurity', 'internet.OnlineBackup', 'internet.DeviceProtection', 'internet.TechSupport', 'internet.StreamingTV', 'internet.StreamingMovies']

Account (contrato/pago/cargos): ['account.Contract', 'account.PaperlessBilling', 'account.PaymentMethod', 'account.Charges.Monthly', 'account.Charges.Total']

In [228]:
#Verificar duplicados
print("Duplicados:", df.duplicated().sum())

Duplicados: 0

In [229]:
#Verificar nulos
print("\nNulos por columna (top 10):")
print(df.isnull().sum().sort_values(ascending=False).head(10))

Nulos por columna (top 10):
customerID                  0
Churn                       0
customer.gender             0
customer.SeniorCitizen      0
customer.Partner            0
customer.Dependents         0
customer.tenure             0
phone.PhoneService          0
phone.MultipleLines         0
internet.InternetService    0
dtype: int64

In [230]:
#Verificar inconsistencias (Valores unicos)
for col in df.columns:
    n = df[col].nunique()
    print(f"Columna: {col} | únicos: {n}")

    if n <= 15:  # más controlado que 50
        print(df[col].unique())
        print("-" * 40)

Columna: customerID | únicos: 7267
Columna: Churn | únicos: 3
['No' 'Yes' '']
----------------------------------------
Columna: customer.gender | únicos: 2
['Female' 'Male']
----------------------------------------
Columna: customer.SeniorCitizen | únicos: 2
[0 1]
----------------------------------------
Columna: customer.Partner | únicos: 2
['Yes' 'No']
----------------------------------------
Columna: customer.Dependents | únicos: 2
['Yes' 'No']
----------------------------------------
Columna: customer.tenure | únicos: 73
Columna: phone.PhoneService | únicos: 2
['Yes' 'No']
----------------------------------------
Columna: phone.MultipleLines | únicos: 3
['No' 'Yes' 'No phone service']
----------------------------------------
Columna: internet.InternetService | únicos: 3
['DSL' 'Fiber optic' 'No']
----------------------------------------
Columna: internet.OnlineSecurity | únicos: 3
['No' 'Yes' 'No internet service']
----------------------------------------
Columna: internet.OnlineBackup | únicos: 3
['Yes' 'No' 'No internet service']
----------------------------------------
Columna: internet.DeviceProtection | únicos: 3
['No' 'Yes' 'No internet service']
----------------------------------------
Columna: internet.TechSupport | únicos: 3
['Yes' 'No' 'No internet service']
----------------------------------------
Columna: internet.StreamingTV | únicos: 3
['Yes' 'No' 'No internet service']
----------------------------------------
Columna: internet.StreamingMovies | únicos: 3
['No' 'Yes' 'No internet service']
----------------------------------------
Columna: account.Contract | únicos: 3
['One year' 'Month-to-month' 'Two year']
----------------------------------------
Columna: account.PaperlessBilling | únicos: 2
['Yes' 'No']
----------------------------------------
Columna: account.PaymentMethod | únicos: 4
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
----------------------------------------
Columna: account.Charges.Monthly | únicos: 1585
Columna: account.Charges.Total | únicos: 6531

In [231]:
#Valores vacios o en blanco
vacios = df.apply(lambda x: x.astype(str).str.strip().eq('').sum())
print("Vacíos (strings) por columna (top 10):")
print(vacios.sort_values(ascending=False).head(10))

Vacíos (strings) por columna (top 10):
Churn                       224
account.Charges.Total        11
customerID                    0
customer.SeniorCitizen        0
customer.gender               0
customer.Partner              0
customer.Dependents           0
phone.PhoneService            0
customer.tenure               0
internet.InternetService      0
dtype: int64

#### Inicia la transformación

In [232]:
#Limpiar churn (Estoy quitando espacios)
df["Churn"] = df["Churn"].astype(str).str.strip()

In [233]:
#Limpiar filas invalidas
df = df[df["Churn"] != ""]

In [234]:
#Eliminando filas donde la columna sea nula
df = df.dropna(subset=["account.Charges.Total"])

In [235]:
#Convierto la columna Charges.Total a numérico (float)
df["account.Charges.Total"] = pd.to_numeric(df["account.Charges.Total"], errors="coerce")
print(df['account.Charges.Total'].dtype)

float64

In [236]:
#Verificando
print("Filas después de limpieza:", df.shape[0])
print("\nNulos (top 10):")
print(df.isnull().sum().sort_values(ascending=False).head(10))
print("\nTipo Charges.Total:", df["account.Charges.Total"].dtype)

Filas después de limpieza: 7043

Nulos (top 10):
account.Charges.Total       11
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customerID                   0
customer.Partner             0
customer.Dependents          0
phone.PhoneService           0
customer.tenure              0
internet.InternetService     0
dtype: int64

Tipo Charges.Total: float64

# Opcional
## Columna de cuentas diarias

In [237]:
# Crear Cuentas_Diarias a partir de Charges.Monthly (Lo divide entre 30 para sacar el valor diario, estimación, por los 30 dias de un mes)
df["Cuentas_Diarias"] = df["account.Charges.Monthly"] / 30

In [238]:
#Verificando
df[["account.Charges.Monthly", "Cuentas_Diarias"]].head()

   account.Charges.Monthly  Cuentas_Diarias
0                     65.6         2.186667
1                     59.9         1.996667
2                     73.9         2.463333
3                     98.0         3.266667
4                     83.9         2.796667

# Opcional 2
## Estandarización y transformación de datos

In [239]:
#Renombrando columnas quitando prefijos del JSON normalizado
df.columns = df.columns.str.replace("customer.", "", regex=False)
df.columns = df.columns.str.replace("phone.", "", regex=False)
df.columns = df.columns.str.replace("internet.", "", regex=False)
df.columns = df.columns.str.replace("account.Charges.", "Charges.", regex=False)
df.columns = df.columns.str.replace("account.", "", regex=False)

In [240]:
#Aqui hago una verificación rápida: mostrar primeras columnas para confirmar el cambio
print("Columnas (muestra):")
print(df.columns[:25])

Columnas (muestra):
Index(['customerID', 'Churn', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Charges.Monthly', 'Charges.Total',
       'Cuentas_Diarias'],
      dtype='object')

In [241]:
#Verifico si faltan columnas del diccionario
cols_diccionario = [
    "customerID","Churn","gender","SeniorCitizen","Partner","Dependents","tenure",
    "PhoneService","MultipleLines","InternetService","OnlineSecurity","OnlineBackup",
    "DeviceProtection","TechSupport","StreamingTV","StreamingMovies","Contract",
    "PaperlessBilling","PaymentMethod","Charges.Monthly","Charges.Total"
]

faltantes = [c for c in cols_diccionario if c not in df.columns]

print("Columnas del diccionario faltantes:", faltantes)

Columnas del diccionario faltantes: []

In [242]:
#Definiendo columnas que depender de Internet
cols_internet = ["OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]

In [243]:
#Reemplazando No internet service por No
for c in cols_internet:
    df[c] = df[c].astype(str).str.strip().replace("No internet service", "No")

In [244]:
#Creando el diccionario de conversión
mapa = {"Yes": 1, "No": 0}

In [245]:
#Definiendo las columnas a convertir
cols_bin = ["Churn","Partner","Dependents","PhoneService","PaperlessBilling"] + cols_internet

In [246]:
#Conversión de columnas
for c in cols_bin:
    df[c] = df[c].astype(str).str.strip().map(mapa)

In [247]:
#Verificando que no quedan nulos
print(df[cols_bin].isna().sum())
df[cols_bin].head()

Churn               0
Partner             0
Dependents          0
PhoneService        0
PaperlessBilling    0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
dtype: int64

,Churn,Partner,Dependents,PhoneService,PaperlessBilling,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,0,1,1,1,1,0,1,0,1,1,0
1,0,0,0,1,0,0,0,0,0,0,1
2,1,0,0,1,1,0,0,1,0,0,0
3,1,1,0,1,1,0,1,1,0,1,1
4,1,1,0,1,1,0,0,0,1,1,0

In [248]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   Churn             7043 non-null   int64
 2   gender            7043 non-null   object
 3   SeniorCitizen     7043 non-null   int64
 4   Partner           7043 non-null   int64
 5   Dependents        7043 non-null   int64
 6   tenure            7043 non-null   int64
 7   PhoneService      7043 non-null   int64
 8   MultipleLines     7043 non-null   object
 9   InternetService   7043 non-null   object
 10  OnlineSecurity    7043 non-null   int64
 11  OnlineBackup      7043 non-null   int64
 12  DeviceProtection  7043 non-null   int64
 13  TechSupport       7043 non-null   int64
 14  StreamingTV       7043 non-null   int64
 15  StreamingMovies   7043 non-null   int64
 16  Contract          7043 non-null   object
 17  PaperlessBilling  7043 non-null   int64
 18  PaymentMethod     7043 non-null   object
 19  Charges.Monthly   7043 non-null   float64
 20  Charges.Total     7032 non-null   float64
 21  Cuentas_Diarias   7043 non-null   float64
dtypes: float64(3), int64(13), object(6)
memory usage: 1.2+ MB

In [249]:
df.isnull().sum().sort_values(ascending=False).head(20)

Charges.Total       11
customerID           0
gender               0
SeniorCitizen        0
Partner              0
Churn                0
Dependents           0
tenure               0
MultipleLines        0
PhoneService         0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
InternetService      0
TechSupport          0
StreamingTV          0
Contract             0
StreamingMovies      0
PaperlessBilling     0
PaymentMethod        0
dtype: int64

In [250]:
#Revisando duplicados
print("Duplicados:", df.duplicated().sum())
print("customerID duplicados:", df["customerID"].duplicated().sum())

Duplicados: 0
customerID duplicados: 0

In [251]:
#Verificando que las columnas binarias solo tengo 1/0
cols_bin = ["Churn","Partner","Dependents","PhoneService","PaperlessBilling",
            "OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]

for c in cols_bin:
    print(c, sorted(df[c].dropna().unique()))

Churn [np.int64(0), np.int64(1)]
Partner [np.int64(0), np.int64(1)]
Dependents [np.int64(0), np.int64(1)]
PhoneService [np.int64(0), np.int64(1)]
PaperlessBilling [np.int64(0), np.int64(1)]
OnlineSecurity [np.int64(0), np.int64(1)]
OnlineBackup [np.int64(0), np.int64(1)]
DeviceProtection [np.int64(0), np.int64(1)]
TechSupport [np.int64(0), np.int64(1)]
StreamingTV [np.int64(0), np.int64(1)]
StreamingMovies [np.int64(0), np.int64(1)]

In [252]:
#Verificando Carges.Total
print(df["Charges.Total"].dtype)
df[["Charges.Monthly","Charges.Total"]].describe()

float64

       Charges.Monthly  Charges.Total
count      7043.000000    7032.000000
mean         64.761692    2283.300441
std          30.090047    2266.771362
min          18.250000      18.800000
25%          35.500000     401.450000
50%          70.350000    1397.475000
75%          89.850000    3794.737500
max         118.750000    8684.800000

In [253]:
df = df.dropna(subset=["Charges.Total"])
print("Filas después de limpiar Charges.Total:", len(df))

Filas después de limpiar Charges.Total: 7032

In [254]:
print("Nulos en Charges.Total:", df["Charges.Total"].isna().sum())

Nulos en Charges.Total: 0

In [255]:
#Verificando Carges.Total de nuevo
print(df["Charges.Total"].dtype)
df[["Charges.Monthly","Charges.Total"]].describe()

float64

       Charges.Monthly  Charges.Total
count      7032.000000    7032.000000
mean         64.798208    2283.300441
std          30.085974    2266.771362
min          18.250000      18.800000
25%          35.587500     401.450000
50%          70.350000    1397.475000
75%          89.862500    3794.737500
max         118.750000    8684.800000

#📊 Carga y análisis

#📄Informe final